settings:
  name: NetApp data services 
  platform: cloud
  search: console-relnotes,console-setup-admin,data-services-backup-recovery,data-services-copy-sync,data-services-classification,data-services-cloud-tiering,data-services-replication,data-services-operational-resiliency,data-services-digital-wallet,data-services-blob-storage,data-services-volume-caching,data-services-disaster-recovery,data-services-ransomware-protection,workload-setup-admin,workload-fsx-ontap,workload-databases,workload-genai,workload-vmware,
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: true
    lipi_enabled: false
sidebar:
  entries:
    - title: "NetApp Console"
      url: ../console-setup-admin/index.html
    - title: Storage management documentation
      url: ../storage-management-family/index.html
    - title: "Release notes"
      url: ../console-relnotes/index.html
    - title: "Backup and Recovery"
      url: ../data-services-backup-recovery/index.html
    - title: "Cloud Tiering"
      url: ../data-services-cloud-tiering/index.html
    - title: "Copy and sync"
      url: ../data-services-copy-sync/index.html
    - title: "Data Classification"
      url: ../data-services-classification/index.html
    - title: "Disaster Recovery"
      url: ../data-services-disaster-recovery/index.html
    - title: "Ransomware Resilience"
      url: ../data-services-ransomware-resilience/index.html 
    - title: "Replication"
      url: ../data-services-replication/index.html
    - title: "Volume Caching"
      url: ../data-services-volume-caching/index.html
    - title: Workloads
      url: ../workload-family
